// Client
export const REQUEST_NEW_GAME = 'REQUEST_NEW_GAME';
export const REQUEST_RECONNECTION = 'REQUEST_RECONNECTION';
export const REQUEST_MOVE_CHARACTER = 'REQUEST_MOVE_CHARACTER';
export const REQUEST_PUSH_TILE = 'REQUEST_PUSH_TILE';
export const REQUEST_COLLECT_ITEM = 'REQUEST_COLLECT_ITEM';

// Server
export const RESPOND_JOINED_ROOM = 'RESPOND_JOINED_ROOM';
export const SEND_WAITING_ELAPSED_TIME = 'SEND_WAITING_ELAPSED_TIME';
export const RESPOND_PLAYER_ADDED_TO_ROOM = 'RESPOND_PLAYER_ADDED_TO_ROOM';
export const PLAYER_DISCONNECTED = 'PLAYER_DISCONNECTED';
export const START_GAME = 'START_GAME';
export const APPROVE_RECONNECTION = 'APPROVE_RECONNECTION';
export const RECONNECTION_FAILED = 'RECONNECTION_FAILED';
export const RESPOND_MOVE_CHARACTER = 'RESPOND_MOVE_CHARACTER';
export const RESPOND_TILE_PUSHED = 'RESPOND_TILE_PUSHED';
export const RESPOND_ITEM_COLLECTED = 'RESPOND_ITEM_COLLECTED';
