export const REQUEST_NEW_GAME = 'REQUEST_NEW_GAME';
export const SEND_JOINED_ROOM = 'SEND_JOINED_ROOM';
export const SEND_WAITING_ELAPSED_TIME = 'SEND_WAITING_ELAPSED_TIME';
export const PLAYER_ADDED_TO_ROOM = 'PLAYER_ADDED_TO_ROOM';
export const START_GAME = 'START_GAME';
