// Assets
export const ADD_LOADED_FONT = 'ADD_LOADED_FONT';
export const ADD_LOADED_ATLAS = 'ADD_LOADED_ATLAS';
export const ADD_LOADED_IMAGE = 'ADD_LOADED_IMAGE';
export const ADD_LOADED_MAP = 'ADD_LOADED_MAPS';
export const ADD_LOADED_JSON = 'ADD_LOADED_JSON';

// Map data
export const SET_MAP_KEY = 'SET_MAP_KEY';
export const ADD_TILESET = 'SET_TILESET';

// Hero data
export const SET_FACING_DIRECTION = 'SET_FACING_DIRECTION';
export const SET_INITIAL_POSITION = 'SET_INITIAL_POSITION';
export const SET_PREVIOUS_POSITION = 'SET_PREVIOUS_POSITION';
export const SET_INITIAL_FRAME = 'SET_INITIAL_FRAME';

// Game settings data
export const SET_GAME_WIDTH = 'SET_GAME_WIDTH';
export const SET_GAME_HEIGHT = 'SET_GAME_HEIGHT';
export const SET_GAME_ZOOM = 'SET_GAME_ZOOM';

// Dialog
export const SET_DIALOG_MESSAGES = 'SET_DIALOG_MESSAGES';
export const SET_DIALOG_ACTION = 'SET_DIALOG_ACTION';
export const SET_DIALOG_CHARACTER_NAME = 'SET_DIALOG_CHARACTER_NAME';

// Menu
export const SET_MENU_ITEMS = 'SET_MENU_ITEMS';
export const SET_MENU_POSITION = 'SET_MENU_POSITION';
export const ADD_MENU_ITEM = 'ADD_MENU_ITEM';
export const SET_MENU_ON_SELECT = 'SET_MENU_ON_SELECT';

// Players
export const ADD_PLAYER = 'ADD_PLAYER';
export const SET_PLAYERS = 'SET_PLAYERS';
export const SET_MY_PLAYER_ID = 'SET_MY_PLAYER_ID';
export const SET_MY_CHARACTER_ID = 'SET_MY_CHARACTER_ID';
export const INCREASE_ITEM_QTY_COLLECTED = 'INCREASE_ITEM_QTY_COLLECTED';

// Game manager
export const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM';
export const ADD_PLAYER_TO_ROOM = 'ADD_PLAYER_TO_ROOM';
export const SET_ROOM_PLAYERS = 'SET_ROOM_PLAYERS';
export const SET_GAME_STARTED = 'SET_GAME_STARTED';
export const SET_ELAPSED_TIME = 'SET_ELAPSED_TIME';
export const INCREASE_ELAPSED_TIME = 'INCREASE_ELAPSED_TIME';
export const SET_PLAYER_IS_CONNECTED = 'SET_PLAYER_IS_CONNECTED';
export const INCREASE_ITEM_QTY_COLLECTED_BY_PLAYER = 'INCREASE_ITEM_QTY_COLLECTED_BY_PLAYER';
