// Assets
export const ADD_LOADED_FONT = 'ADD_LOADED_FONT';
export const ADD_LOADED_ATLAS = 'ADD_LOADED_ATLAS';
export const ADD_LOADED_IMAGE = 'ADD_LOADED_IMAGE';
export const ADD_LOADED_MAP = 'ADD_LOADED_MAPS';
export const ADD_LOADED_JSON = 'ADD_LOADED_JSON';

// Map data
export const SET_MAP_KEY = 'SET_MAP_KEY';
export const ADD_TILESET = 'SET_TILESET';

// Hero data
export const SET_FACING_DIRECTION = 'SET_FACING_DIRECTION';
export const SET_INITIAL_POSITION = 'SET_INITIAL_POSITION';
export const SET_PREVIOUS_POSITION = 'SET_PREVIOUS_POSITION';
export const SET_INITIAL_FRAME = 'SET_INITIAL_FRAME';

// Game data
export const SET_GAME_WIDTH = 'SET_GAME_WIDTH';
export const SET_GAME_HEIGHT = 'SET_GAME_HEIGHT';
export const SET_GAME_ZOOM = 'SET_GAME_ZOOM';
